slurm:
    wall_time: "23:59:00"
    atoms_per_processor: 6
    max_processors: 20
    ram_per_processor: 2

mongoDB:
    host: "128.112.127.215"
    port: 27017
    user: "autoqchem"
    password: "dftworks"
